### PR TITLE
[loop_tool] WIP upgrade the action space

### PR DESCRIPTION
**Pull request by bwasti**
General upgrade using the new loop_tool API and the new CompilerGym API

### CODE REVIEW

**Comment by bwasti** [comment]
I'm hitting this error:

```
        # If the action space has changed, update it.
        if reply.HasField("new_action_space"):
            self.action_space, self._make_action = proto_to_action_space(
>               reply.action_space
            )
E           AttributeError: action_space

compiler_gym/envs/compiler_env.py:978: AttributeError
```

**Comment by ChrisCummins** [comment]
> I'm hitting this error:

Hmm, I think I fixed that in your PR #479. I had a few patches to fix this error and some others I found. I think they may have been lost in a force push. Here is the ref, check out my set of patches from Nov 10: https://github.com/facebookresearch/CompilerGym/commits/3870fce946062e1b9e3f9840d225e23492ff3e55

Cheers,
Chris

**Comment by ChrisCummins** [comment]
(the commit that fixes the error you listed is 5ccbeceea25b392a1704add4d1b07741e574325d, but there were other fixes too)

**Comment by ChrisCummins** [comment]
Closing as inactive. Feel free to reopen @bwasti.

**Pull request closed without merging**
