### PR TITLE
Leaderboard implementation of tabular Q

### PR DESCRIPTION
**Pull request by JD-ETH**
@ChrisCummins I am encountering this error during compilation, and I have been using the most recent development branch and up-to-date pip package of compiler gym. 

```
Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/sandbox/darwin-sandbox/19/execroot/CompilerGym/bazel-out/host/bin/compiler_gym/envs/llvm/make_specs.runfiles/CompilerGym/compiler_gym/envs/llvm/make_specs.py", line 10, in <module>
    from compiler_gym.envs.llvm.llvm_env import LlvmEnv
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/sandbox/darwin-sandbox/19/execroot/CompilerGym/bazel-out/host/bin/compiler_gym/envs/llvm/make_specs.runfiles/CompilerGym/compiler_gym/envs/llvm/llvm_env.py", line 15, in <module>
    from compiler_gym.envs.compiler_env import CompilerEnv
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/sandbox/darwin-sandbox/19/execroot/CompilerGym/bazel-out/host/bin/compiler_gym/envs/llvm/make_specs.runfiles/CompilerGym/compiler_gym/envs/compiler_env.py", line 24, in <module>
    from compiler_gym.datasets.dataset import LegacyDataset, require
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/sandbox/darwin-sandbox/19/execroot/CompilerGym/bazel-out/host/bin/compiler_gym/envs/llvm/make_specs.runfiles/CompilerGym/compiler_gym/datasets/dataset.py", line 15, in <module>
    from deprecated.sphinx import deprecated
ModuleNotFoundError: No module named 'deprecated'
```

Decided to make it a PR so that you have context as well.

### CODE REVIEW

**Comment by ChrisCummins** [comment]
The development branch has a new dependency that the version on pip does not have, so the module is missing. Run `make init` from the root of the repo to grab all of the python dependencies.

Cheers,
Chris

**Comment by JD-ETH** [comment]
Thanks, it works! Funny to call a package `deprecated`...

**Comment by JD-ETH** [comment]
I'm facing this error during the evaluation:  
```
Resulting sequence:  -break-crit-edges,-newgvn,-simplifycfg,-sroa,-instcombine total reward 0.9352701325178389
 13%|██████████████████████████▊                                                                                                                                                                                   | 30/230 [29:27<3:16:25, 58.93s/ benchmark]Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/execroot/CompilerGym/bazel-out/darwin-opt/bin/leaderboard/llvm_codesize/tabular_q/tabular_q_eval.runfiles/CompilerGym/leaderboard/llvm_codesize/eval_policy.py", line 139, in run
    self.policy(self.env)
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/execroot/CompilerGym/bazel-out/darwin-opt/bin/leaderboard/llvm_codesize/tabular_q/tabular_q_eval.runfiles/CompilerGym/leaderboard/llvm_codesize/tabular_q/tabular_q_eval.py", line 19, in train_and_run
    train(q_table, training_env)
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/execroot/CompilerGym/bazel-out/darwin-opt/bin/leaderboard/llvm_codesize/tabular_q/tabular_q_eval.runfiles/CompilerGym/examples/tabular_q.py", line 149, in train
    observation = env.observation["Autophase"]
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/execroot/CompilerGym/bazel-out/darwin-opt/bin/leaderboard/llvm_codesize/tabular_q/tabular_q_eval.runfiles/CompilerGym/compiler_gym/views/observation.py", line 56, in __getitem__
    reply: StepReply = self._get_observation(request)
  File "/private/var/tmp/_bazel_jdguo/7889602d80c1d2c23f0de266ae0d59dd/execroot/CompilerGym/bazel-out/darwin-opt/bin/leaderboard/llvm_codesize/tabular_q/tabular_q_eval.runfiles/CompilerGym/compiler_gym/envs/compiler_env.py", line 279, in <lambda>
    get_observation=lambda req: self.service(self.service.stub.Step, req),
AttributeError: 'NoneType' object has no attribute 'stub'
```

Not sure why this is happening, also the iteration seems to slow down. Is there a way to identify the issue? @ChrisCummins

**Comment by JD-ETH** [comment]
this seems to happen consistently at 30th evaluations.

**Comment by ChrisCummins** [comment]
> I'm facing this error during the evaluation:

Yep, that's a strange one. The fact that it happens consistently on the 30th evaluation implies that it's a problem with the third benchmark (the benchmarks are always evaluted in the same order, and the default `--n` flag runs each benchmark 10 times.

Can you confirm that you're running this via bazel on the latest development branch?

Cheers,
Chris

**Comment by ChrisCummins** [comment]
LGTM, thanks for this @JD-ETH! Feel free to merge when happy.

Cheers,
Chris

**Pull request merged**
