### PR TITLE
timeout programl build

### PR DESCRIPTION
**Pull request by mostafaelhoushi**
Temporary workaround for https://github.com/facebookresearch/CompilerGym/issues/566

### CODE REVIEW

**Comment by mostafaelhoushi** [comment]
Build-linux-cmake paased but took more than 3.5 hours. So will abandon this PR.

**Comment by ChrisCummins** [comment]
Interesting! So perhaps the problem is not with bazel?

**Comment by mostafaelhoushi** [comment]
> Interesting! So perhaps the problem is not with bazel?

I am not sure. I will double check by reducing the timeout from 30m to like 30 seconds to check if the timeout takes effect.

On another note, in my own Linux build, it seems to hang somewhere during the build of Programl or at the end of of building Programl? See the screenshot below:
image

**Comment by ChrisCummins** [comment]
> On another note, in my own Linux build, it seems to hang somewhere during the build of Programl or at the end of of building Programl? See the screenshot below:

Yeah that's the same problem as the CI is encountering, so its good that you can reproduce it locally. I believe you could probably delete the programl subdir in the `build/` directory to force a quick rebuild, rather than having to wait for the CI to do a full build

Cheers,
Chris

**Comment by mostafaelhoushi** [comment]
Abandoning this PR as it seems the problem is solved in #703

**Pull request closed without merging**
