### PR TITLE
[www] Sahir/UI/code_cleanup

### PR DESCRIPTION
**Pull request by sahirgomez1**
This PR fixes:

- UI bugs on Node v17
- Adds favicons.
- Bumps up react-bootstrap to latest version.
- Styled components.

### CODE REVIEW

**Comment by ChrisCummins** [comment]
Code LGTM! But the `CI/www-build` job is failing with error:

```
/opt/hostedtoolcache/node/16.14.0/x64/bin/node: bad option: --openssl-legacy-provider
```

Any idea what is going on there?

**Comment by sahirgomez1** [comment]
> 

@ChrisCummins you might need to bump up the `CI` to Node 17. 

see [here](https://nodejs.org/en/blog/release/v17.0.0/#:~:text=command%2Dline%20option%2C-,%2D%2Dopenssl%2Dlegacy%2Dprovider,-%2C%20has%20been%20added)

**Comment by ChrisCummins** [comment]
> > 
> 
> @ChrisCummins you might need to bump up the `CI` to Node 17.
> 
> see [here](https://nodejs.org/en/blog/release/v17.0.0/#:~:text=command%2Dline%20option%2C-,%2D%2Dopenssl%2Dlegacy%2Dprovider,-%2C%20has%20been%20added)

Could you take a look at this? Node version declared here:

https://github.com/facebookresearch/CompilerGym/blob/development/.github/workflows/ci.yaml#L607

Thanks!

**Comment by sahirgomez1** [comment]
> 

Understood. Fixed now.

**Comment by ChrisCummins** [comment]
Many thanks!

**Pull request merged**
