### PR TITLE
Bambu

### PR DESCRIPTION
**Pull request by ibrumar**
Committing the parsing of the Bambu infrastructure to the compiler gym infrastructure.

At this point the focus is on the area reduction aspect.

Some items to improve:
-generalize bambu path.
-generalize the function to synthesize instead of the hardcoded function.
-incorporate development branch commits.

### CODE REVIEW

**Comment by ChrisCummins** [comment]
Hi @ibrumar, I have rebased my local copy of this branch onto the latest development but I am blocked until I can get a copy of bambu for testing.

Cheers,
Chris

**Comment by ibrumar** [comment]
> Hi @ibrumar, I have rebased my local copy of this branch onto the latest development but I am blocked until I can get a copy of bambu for testing.
> 
> Cheers, Chris

Hi @ChrisCummins, sounds good. Would it make sense to try to create a Linux+X86 binary? I can have a look at it.

**Comment by ChrisCummins** [comment]
Hi @ibrumar, yes that would be perfect! I use a docker image based on Ubuntu 18.04 to build the release binaries for CompilerGym. If you run `make bdist_wheel-linux-shell` this will drop you into a bash prompt in that environment. The directory `/CompilerGym` in the container is mapped to your CompilerGym repo on the host. Lemme know if you have any questions.

You can take a look at the Makefile rules if you'd like more context: https://github.com/facebookresearch/CompilerGym/blob/development/Makefile#L205

Take a look at this Github actions workflow for building the CompilerGym release binaries. We could adapt that to your bambu build so that it can build a macOS + linux binary release on-demand: https://github.com/facebookresearch/CompilerGym/blob/development/.github/workflows/build.yaml#L33-L54

Cheers,
Chris

**Comment by ChrisCummins** [comment]
@ibrumar, are you interested in continuing work on this?

**Comment by ibrumar** [comment]
@ChrisCummins, let me get back to this in a couple of days.

**Comment by ChrisCummins** [comment]
Closing as inactive. Feel free to reopen @ibrumar.

**Pull request closed without merging**
