### PR TITLE
Include name in space comparison

### PR DESCRIPTION
**Pull request by sogartar**
I am not entirely sure if this is the desired behavior.

### CODE REVIEW

**Review by ChrisCummins — COMMENTED** [review]
This seems reasonable. I can't think of a why you wouldn't want to compare on name.

Could you add a positive and negative unit test for each of the `__eq__` operators?

Cheers,
Chris

**Comment by sogartar** [comment]
> Could you add a positive and negative unit test for each of the `__eq__` operators?

Done.

**Comment by ChrisCummins** [comment]
Thanks a lot!

The `id` argument for `Reward` is deprecated. If you remove them that should fix the CI, then this looks ready to merge.

Cheers,
Chris

**Comment by sogartar** [comment]
> The `id` argument for `Reward` is deprecated. If you remove them that should fix the CI, then this looks ready to merge.

I removed it and fixed the other tests.

**Review by ChrisCummins — APPROVED** [review]
LGTM, thanks @sogartar!

**Pull request merged**
