### PR TITLE
Rename Reward.id to Reward.name

### PR DESCRIPTION
**Pull request by PuneetDabral**
Fixes #{381}
sir, please check and review

### CODE REVIEW

**Comment by PuneetDabral** [comment]
already signed in...but it shows the same error

**Comment by ChrisCummins** [comment]
Hi @PuneetDabral, that's not quite right. The goal of #381 is to change `Reward.id` to `Reward.name`:

```diff
-     self.id = id
+     self.name = name
```

In your commit, you have only changed the name of a single reference to the `id` variable. You will need to update all references to `Reward.id` to the new name. Use the test suite to make sure everything still works. See [my comment here](https://github.com/facebookresearch/CompilerGym/issues/381#issuecomment-915925958) for further details.

Cheers,
Chris

**Comment by PuneetDabral** [comment]
now it is ok sir....can you please check this

**Comment by ChrisCummins** [comment]
Hi @PuneetDabral, it looks like this is incomplete, with many tests failing. Have you followed the advice I provided above about setting up a local environment to run the tests?

Cheers,
Chris

**Comment by PuneetDabral** [comment]
sir i does not work.. i am totally confuse

**Comment by ChrisCummins** [comment]
Hi @PuneetDabral, please follow the installation instructions [here](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md) so that you can run the test suite locally. By fixing the errors in the failing tests this will help you complete this task.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Closing this due to inactivity. If you'd like to continue working on this please refile a PR :-)

**Pull request closed without merging**
