### PR TITLE
Enable and Fix Environment Examples in CMake CI

### LINKED ISSUE #631: examples/loop_optimizations_service/env_tests.py::test_default_autophase_dict_observation fails
## 🐛 Bug

On my machine the test `examples/loop_optimizations_service/env_tests.py::test_default_autophase_dict_observation` is failing with
```
=================================== FAILURES ===================================
___________________ test_default_autophase_dict_observation ____________________

env = <compiler_gym.envs.compiler_env.CompilerEnv object at 0x7f7d2c61fa00>

    def test_default_autophase_dict_observation(env: CompilerEnv):
        """Test default autophase dict observation space."""
        env.observation_space = "AutophaseDict"
        observation = env.reset()
        assert isinstance(observation, dict)
>       assert observation.keys() == AUTOPHASE_FEATURE_NAMES
E       AssertionError: assert dict_keys(['NumGetElementPtrInst', 'numConstOnes', 'NumLShrInst', 'NumICmpInst', 'binaryConstArg', 'NumStoreInst', 'NumCallInst', 'const64Bit', 'oneSuccessor', 'BranchCount', 'TotalMemInst', 'NumXorInst', 'NumZExtInst', 'NumAllocaInst', 'BBNumArgsLo', 'BlockLow', 'NumAShrInst', 'morePreds', 'NumAddInst', 'onePredTwoSuc', 'ArgsPhi', 'NumSubInst', 'const32Bit', 'NumOrInst', 'CriticalCount', 'NumShlInst', 'onePred', 'BeginPhi', 'NumEdges', 'BlockMid', 'NumRetInst', 'NumTruncInst', 'testUnary', 'twoPred', 'twoSuccessor', 'TotalFuncs', 'NumPHIInst', 'NumSExtInst', 'BBHiPhi', 'BBNumArgsHi', 'BB03Phi', 'NumLoadInst', 'numConstZeroes', 'UncondBranches', 'NumMulInst', 'returnInt', 'NumAndInst', 'NumBrInst', 'BBNoPhi', 'onePredOneSuc', 'TotalBlocks', 'NumBitCastInst', 'NumSelectInst', 'TotalInsts', 'twoPredOneSuc', 'twoEach']) == ['BBNumArgsHi',\n 'BBNumArgsLo',\n 'onePred',\n 'onePredOneSuc',\n 'onePredTwoSuc',\n 'oneSuccessor',\n 'twoPred',\n 'twoPredOneSuc',\n 'twoEach',\n 'twoSuccessor',\n 'morePreds',\n 'BB03Phi',\n 'BBHiPhi',\n 'BBNoPhi',\n 'BeginPhi',\n 'BranchCount',\n 'returnInt',\n 'CriticalCount',\n 'NumEdges',\n 'const32Bit',\n 'const64Bit',\n 'numConstZeroes',\n 'numConstOnes',\n 'UncondBranches',\n 'binaryConstArg',\n 'NumAShrInst',\n 'NumAddInst',\n 'NumAllocaInst',\n 'NumAndInst',\n 'BlockMid',\n 'BlockLow',\n 'NumBitCastInst',\n 'NumBrInst',\n 'NumCallInst',\n 'NumGetElementPtrInst',\n 'NumICmpInst',\n 'NumLShrInst',\n 'NumLoadInst',\n 'NumMulInst',\n 'NumOrInst',\n 'NumPHIInst',\n 'NumRetInst',\n 'NumSExtInst',\n 'NumSelectInst',\n 'NumShlInst',\n 'NumStoreInst',\n 'NumSubInst',\n 'NumTruncInst',\n 'NumXorInst',\n 'NumZExtInst',\n 'TotalBlocks',\n 'TotalInsts',\n 'TotalMemInst',\n 'TotalFuncs',\n 'ArgsPhi',\n 'testUnary']
E         +dict_keys(['NumGetElementPtrInst', 'numConstOnes', 'NumLShrInst', 'NumICmpInst', 'binaryConstArg', 'NumStoreInst', 'NumCallInst', 'const64Bit', 'oneSuccessor', 'BranchCount', 'TotalMemInst', 'NumXorInst', 'NumZExtInst', 'NumAllocaInst', 'BBNumArgsLo', 'BlockLow', 'NumAShrInst', 'morePreds', 'NumAddInst', 'onePredTwoSuc', 'ArgsPhi', 'NumSubInst', 'const32Bit', 'NumOrInst', 'CriticalCount', 'NumShlInst', 'onePred', 'BeginPhi', 'NumEdges', 'BlockMid', 'NumRetInst', 'NumTruncInst', 'testUnary', 'twoPred', 'twoSuccessor', 'TotalFuncs', 'NumPHIInst', 'NumSExtInst', 'BBHiPhi', 'BBNumArgsHi', 'BB03Phi', 'NumLoadInst', 'numConstZeroes', 'UncondBranches', 'NumMulInst', 'returnInt', 'NumAndInst', 'NumBrInst', 'BBNoPhi', 'onePredOneSuc', 'TotalBlocks', 'NumBitCastInst', 'NumSelectInst', 'TotalInsts', 'twoPredOneSuc', 'twoEach'])
E         -['BBNumArgsHi', 'BBNumArgsLo', 'onePred', 'onePredOneSuc', 'onePredTwoSuc', 'oneSuccessor', 'twoPred', 'twoPredOneSuc', 'twoEach', 'twoSuccessor', 'morePreds', 'BB03Phi', 'BBHiPhi', 'BBNoPhi', 'BeginPhi', 'BranchCount', 'returnInt', 'CriticalCount', 'NumEdges', 'const32Bit', 'const64Bit', 'numConstZeroes', 'numConstOnes', 'UncondBranches', 'binaryConstArg', 'NumAShrInst', 'NumAddInst', 'NumAllocaInst', 'NumAndInst', 'BlockMid', 'BlockLow', 'NumBitCastInst', 'NumBrInst', 'NumCallInst', 'NumGetElementPtrInst', 'NumICmpInst', 'NumLShrInst', 'NumLoadInst', 'NumMulInst', 'NumOrInst', 'NumPHIInst', 'NumRetInst', 'NumSExtInst', 'NumSelectInst', 'NumShlInst', 'NumStoreInst', 'NumSubInst', 'NumTruncInst', 'NumXorInst', 'NumZExtInst', 'TotalBlocks', 'TotalInsts', 'TotalMemInst', 'TotalFuncs', 'ArgsPhi', 'testUnary']
E         Full diff:
E         + dict_keys(['NumGetElementPtrInst', 'numConstOnes', 'NumLShrInst', 'NumICmpInst', 'binaryConstArg', 'NumStoreInst', 'NumCallInst', 'const64Bit', 'oneSuccessor', 'BranchCount', 'TotalMemInst', 'NumXorInst', 'NumZExtInst', 'NumAllocaInst', 'BBNumArgsLo', 'BlockLow', 'NumAShrInst', 'morePreds', 'NumAddInst', 'onePredTwoSuc', 'ArgsPhi', 'NumSubInst', 'const32Bit', 'NumOrInst', 'CriticalCount', 'NumShlInst', 'onePred', 'BeginPhi', 'NumEdges', 'BlockMid', 'NumRetInst', 'NumTruncInst', 'testUnary', 'twoPred', 'twoSuccessor', 'TotalFuncs', 'NumPHIInst', 'NumSExtInst', 'BBHiPhi', 'BBNumArgsHi', 'BB03Phi', 'NumLoadInst', 'numConstZeroes', 'UncondBranches', 'NumMulInst', 'returnInt', 'NumAndInst', 'NumBrInst', 'BBNoPhi', 'onePredOneSuc', 'TotalBlocks', 'NumBitCastInst', 'NumSelectInst', 'TotalInsts', 'twoPredOneSuc', 'twoEach'],
E         + )
E         - [
E         -  'BBNumArgsHi',
E         -  'BBNumArgsLo',
E         -  'onePred',
E         -  'onePredOneSuc',
E         -  'onePredTwoSuc',
E         -  'oneSuccessor',
E         -  'twoPred',
E         -  'twoPredOneSuc',
E         -  'twoEach',
E         -  'twoSuccessor',
E         -  'morePreds',
E         -  'BB03Phi',
E         -  'BBHiPhi',
E         -  'BBNoPhi',
E         -  'BeginPhi',
E         -  'BranchCount',
E         -  'returnInt',
E         -  'CriticalCount',
E         -  'NumEdges',
E         -  'const32Bit',
E         -  'const64Bit',
E         -  'numConstZeroes',
E         -  'numConstOnes',
E         -  'UncondBranches',
E         -  'binaryConstArg',
E         -  'NumAShrInst',
E         -  'NumAddInst',
E         -  'NumAllocaInst',
E         -  'NumAndInst',
E         -  'BlockMid',
E         -  'BlockLow',
E         -  'NumBitCastInst',
E         -  'NumBrInst',
E         -  'NumCallInst',
E         -  'NumGetElementPtrInst',
E         -  'NumICmpInst',
E         -  'NumLShrInst',
E         -  'NumLoadInst',
E         -  'NumMulInst',
E         -  'NumOrInst',
E         -  'NumPHIInst',
E         -  'NumRetInst',
E         -  'NumSExtInst',
E         -  'NumSelectInst',
E         -  'NumShlInst',
E         -  'NumStoreInst',
E         -  'NumSubInst',
E         -  'NumTruncInst',
E         -  'NumXorInst',
E         -  'NumZExtInst',
E         -  'TotalBlocks',
E         -  'TotalInsts',
E         -  'TotalMemInst',
E         -  'TotalFuncs',
E         -  'ArgsPhi',
E         -  'testUnary',
E         - ]

examples/loop_optimizations_service/env_tests.py:227: AssertionError
---------------------------- Captured stderr setup -----------------------------
I0318 15:25:23.493640 140334948332352 create_and_run_compiler_gym_service.py:117] Service /dev/shm/compiler_gym_petkantchin/s/0318T152523-164730-47dd listening on 34091, PID = 2809987
I0318 15:25:23.542277 140334175786752 compiler_gym_service.py:105] GetSpaces()
----------------------------- Captured stderr call -----------------------------
I0318 15:25:23.550705 140334175786752 compiler_gym_service.py:114] StartSession(id=0, benchmark=benchmark://loops-opt-v0/add), 1 active sessions
I0318 15:25:23.553207 140334175786752 benchmark_cache.py:76] Cached benchmark benchmark://loops-opt-v0/add. Cache size = 22508 bytes, 1 items
I0318 15:25:23.554704 140334175786752 compiler_gym_service.py:114] StartSession(id=0, benchmark=benchmark://loops-opt-v0/add), 1 active sessions
I0318 15:25:23.554952 140334175786752 loops_opt_service.py:148] Started a compilation session for benchmark://loops-opt-v0/add
I0318 15:25:23.579383 140334175786752 loops_opt_service.py:261] Computing observation from space AutophaseDict
I0318 15:25:23.589350 140334175786752 compiler_gym_service.py:188] Step()
I0318 15:25:23.589824 140334175786752 loops_opt_service.py:261] Computing observation from space runtime
I0318 15:25:23.980890 140334175786752 compiler_gym_service.py:188] Step()
I0318 15:25:23.981082 140334175786752 loops_opt_service.py:261] Computing observation from space size
--------------------------- Captured stderr teardown ---------------------------
I0318 15:25:24.056299 140334175786752 compiler_gym_service.py:176] EndSession(id=0), 0 sessions remaining
I0318 15:25:24.056845 140334948332352 create_and_run_compiler_gym_service.py:48] Service received signal: 15
I0318 15:25:24.057053 140334948332352 create_and_run_compiler_gym_service.py:130] Shutting down the RPC service
I0318 15:25:24.057943 140334948332352 create_and_run_compiler_gym_service.py:133] Service closed
=========================== short test summary info ============================
FAILED examples/loop_optimizations_service/env_tests.py::test_default_autophase_dict_observation
======================== 1 failed, 22 passed in 18.68s =========================
```
This happens on commit d22fd363845b9f1958d7904b911516470f8d1b55.
I am not sure why it does not fail on the CI, does it even run there?

## To Reproduce

Run in source directory
```
bazel run //examples/loop_optimizations_service:env_tests
```

## Environment

- CompilerGym:
- How you installed CompilerGym (conda, pip, source): source
- OS: Ubuntu 20.04
- Python version: 3.8.12
- Build command you used (if compiling from source): `bazel run`
- GCC/clang version (if compiling from source): GCC 9.4.0 and clang 12.0.0
- Bazel version (if compiling from source): 4.2.2
- Versions of any other relevant libraries:

### PR DESCRIPTION
**Pull request by mostafaelhoushi**
Fixes #631

- ensured that the example scripts are invoked in CMake CI by creating `example_without_bazel_test.py` scripts
- ensured that unit tests in `env_tests.py` are invoked in CMake CI by copying them into `env_without_bazel_test.py`
- disabled the tests cases in Linux and MacOS bazel builds for now (hopefully will fix that with #707 )

### CODE REVIEW

**Comment by ChrisCummins** [comment]
Looks like the CI is broken on this

**Comment by mostafaelhoushi** [comment]
I am revisiting this pull request.
So the CI runs the tests by calling `make -C example tests` which in turn runs the Python tests without bazel.
The tests run fine if I use bazel, e.g.,
```
bazel test //examples/example_compiler_gym_service/...
```
but running the Python files direcrtly doesn't work.


So I had to follow the approach we did when we copied `demo.py` to `demo_without_bazel.py`, so here I am copying `env_test.py` to `env_without_bazel_test.py` and made some changes accordingly.

However, I am now stuck with this error:
```
$ cd examples
$ python example_compiler_gym_service/env_without_bazel_test.py                            
======================================================================= test session starts ========================================================================
platform darwin -- Python 3.8.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /Users/melhoushi/opt/anaconda3/envs/compiler_gym/bin/python
cachedir: .pytest_cache
rootdir: /Users/melhoushi/CompilerGym, configfile: tox.ini
plugins: flaky-3.7.0, hydra-core-1.1.0
collected 0 items / 1 error                                                                                                                                        
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1210, in pytest_collection
INTERNALERROR>     self._validate_config_options()
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1233, in _validate_config_options
INTERNALERROR>     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1269, in _warn_or_fail_if_strict
INTERNALERROR>     self.issue_config_time_warning(PytestConfigWarning(message), stacklevel=3)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1321, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: timeout

========================================================================= 1 error in 0.16s =========================================================================
```

**Comment by ChrisCummins** [comment]
That's a strange one. Looks like maybe a problem with missing / bad plugin?

If you disable `env_without_bazel_test.py` (by renaming it `foo.py`), does the problem go away?

**Comment by mostafaelhoushi** [comment]
> That's a strange one. Looks like maybe a problem with missing / bad plugin?
> 
> If you disable `env_without_bazel_test.py` (by renaming it `foo.py`), does the problem go away?

Got the same error :(

```
$ mv example_compiler_gym_service/env_without_bazel_test.py example_compiler_gym_service/foo.py
$ python example_compiler_gym_service/foo.py 

======================================================================= test session starts ========================================================================
platform darwin -- Python 3.8.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /Users/melhoushi/opt/anaconda3/envs/compiler_gym/bin/python
cachedir: .pytest_cache
rootdir: /Users/melhoushi/CompilerGym, configfile: tox.ini
plugins: flaky-3.7.0, hydra-core-1.1.0
collected 0 items / 1 error                                                                                                                                        
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1210, in pytest_collection
INTERNALERROR>     self._validate_config_options()
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1233, in _validate_config_options
INTERNALERROR>     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1269, in _warn_or_fail_if_strict
INTERNALERROR>     self.issue_config_time_warning(PytestConfigWarning(message), stacklevel=3)
INTERNALERROR>   File "/Users/melhoushi/opt/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1321, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: timeout

========================================================================= 1 error in 0.15s =========================================================================
```

**Comment by mostafaelhoushi** [comment]
Never mind.. when I installed:
```
$ pip install pytest-timeout==1.4.2  
```
I no longer got the error....

Now fixing other errors :)

**Comment by mostafaelhoushi** [comment]
@ChrisCummins : do you know why the pre-commit job is failing? It seems to be not related to this PR:
image

**Comment by ChrisCummins** [comment]
Copy the `examples/sensitivity_analysis` dir from latest development head

I broke it yesterday, should be fixed now 🙂

**Comment by ChrisCummins** [comment]
Ah, sorry, I was confused! The `development` branch is still broken. I'll merge an update now so that you can rebase this branch on it. Stay tuned ...

**Comment by ChrisCummins** [comment]
Okay, `development` is now un-broken. Off to the races!

**Comment by mostafaelhoushi** [comment]
The CI is failing with `WARNING: Overriding environment example-v0`. 
image

I was able to mitigate that on my local machine by adding those arguments when calling `main` (full context [here](https://github.com/mostafaelhoushi/CompilerGym/blob/enable-examples-tests-in-ci/examples/example_compiler_gym_service/env_without_bazel_test.py#L448-L454
)):
```
if __name__ == "__main__":
    main(
        extra_pytest_args=[
            "-W",
            "ignore::UserWarning",
        ]
    )
```

I am not sure why it still fails on CI.

Any idea @ChrisCummins ?

**Comment by ChrisCummins** [comment]
Hmm, not sure about this one. Will have to take a look on Tuesday.

Cheers,
Chris

**Comment by mostafaelhoushi** [comment]
OK. I fixed it in this commit https://github.com/facebookresearch/CompilerGym/pull/642/commits/0077632ed5350284f9faeb4b2600d5fe9d867977 by choosing a different name for the registered environment in `env_without_bazel_test.py` from `example-v0` to `example-v1`.

(Perhaps the error is due to `demo_without_bazel_test.py` running before `env_without_bazel_test.py` creating an environment with the same name `example-v0`).

**Comment by ChrisCummins** [comment]
Ah, that makes sense. Every environment you register must have a unique name. So if two tests register `example-v0`, one will clobber the other when all of the tests are run in a single python session.

Cheers,
Chris

**Comment by mostafaelhoushi** [comment]
@ChrisCummins , `test-examples-macos` failed with:
```
        if done:
            # Computing an observation should never cause a terminal state since
            # no action has been applied.
            msg = f"Failed to compute observation '{observation_space.id}'"
            if info.get("error_details"):
                msg += f": {info['error_details']}"
>           raise ServiceError(msg)
E           compiler_gym.errors.service_errors.ServiceError: Failed to compute observation 'runtime': RPC call returned status code StatusCode.INTERNAL and error `Compilation job failed with returncode 1 (SIGHUP)
E           Command: /Users/runner/.local/share/compiler_gym/llvm-v0/bin/clang /Users/runner/.local/cache/compiler_gym/s/0613T160607-720121-389c/benchmark.o -O3 -o /Users/runner/.local/cache/compiler_gym/s/0613T160607-720121-389c/benchmark.exe
E           Stderr: ld: library not found for -lSystem
E           clang: error: linker command failed with exit code 1 (use -v to see invocation)`
```

do you know a fix for that? 

(Full log should be here: https://github.com/facebookresearch/CompilerGym/runs/6865005685?check_suite_focus=true)

**Comment by ChrisCummins** [comment]
Yep. The LLVM binaries we use for CompilerGym don't know about the system libraries, we need to figure them out ourselves. To do this, call [compiler_gym.envs.llvm.get_system_library_flags()](https://compilergym.com/llvm/api.html#compiler_gym.envs.llvm.get_system_library_flags) and append the list of flags it returns to your clang invocation(s).

Cheers,
Chris

**Comment by mostafaelhoushi** [comment]
I have removed the explicit run of python examples in CI, and ensured that they run in pytest instead.

I have disabled the tests cases in Linux and MacOS bazel builds for now (hopefully will fix that with #707 ).

The Pull Request should be ready now for review @ChrisCummins

**Comment by ChrisCummins** [comment]
LGTM. Many thanks for pushing on this @mostafaelhoushi.

Feel free to merge when you're happy with it.

Cheers,
Chris

**Pull request merged**
